# Generated by Django 2.2.14 on 2021-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210327_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='payment_option',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'Biling'), ('S', 'Shipping')], max_length=1),
        ),
    ]
